=== miquelmarques/LMSGI_DTD/RA01-RA04 Activitat/Exercisi1.d.dtd
<!ELEMENT joc (titol, companyia, plataforma+, anyLlançament, modesJoc, regions, personatges)>
<!ELEMENT titol (PCDATA)>
<!ELEMENT companyia (PCDATA)>
<!ELEMENT plataforma (PCDATA)>
<!ELEMENT anyLlançament (PCDATA)>
<!ELEMENT modesJoc (mode+)>
<!ELEMENT mode (PCDATA)>
<!ELEMENT personatges (personatge+)>
<!ELEMENT personatge (nom)>
<!ELEMENT regions (regio+)>
<!ELEMENT regio (nom, nota?)>
<!ELEMENT nota (PCDATA)>
<!ELEMENT nom (PCDATA)>
<!ATTLIST mode principal (si|no) #REQUIRED>
<!ATTLIST personatge tipus CDATA #REQUIRED>
<!ATTLIST personatge jugable (si|no) #REQUIRED>
<!ATTLIST regio clima CDATA #REQUIRED>

=== miquelmarques/LMSGI_DTD/Exercisi1.d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "Exercisi1.d.dtd">
<joc>
    <titol>The Legend of Zelda: Breath of the Wild</titol>
    <companyia>Nintendo</companyia>
    <plataforma>Nintendo Switch</plataforma>
    <anyLlançament>2017</anyLlançament>
    <modesJoc>
        <mode principal="si">Món obert</mode>
        <mode principal="no">Santuari</mode>
        <mode principal="no">Combat contra caps</mode>
    </modesJoc>
    <personatges>
        <personatge tipus="heroi" jugable="si">
            <nom>Link</nom>
        </personatge>
        <personatge tipus="princesa" jugable="no">
            <nom>Zelda</nom>
        </personatge>
        <personatge tipus="antagonista" jugable="no">
            <nom>Ganon</nom>
        </personatge>
    </personatges>
    <regions>
        <regio clima="fred">
            <nom>Hebra</nom>
        </regio>
        <regio clima="càlid">
            <nom>Gerudo</nom>
        </regio>
        <regio clima="neutre">
            <nom>Centre d'Hyrule</nom>
            <nota>Zona amb molts guardians.</nota>
        </regio>
    </regions>
</joc>
