=== miquelmarques/LMSGI_DTD/RA01-RA04 Activitat/Exercisi1.b.dtd
<!ELEMENT joc (titol,companyia, plataforma+, anyLlançament, personatges)>
<!ELEMENT titol (PCDATA)>
<!ELEMENT companyia (PCDATA)>
<!ELEMENT plataforma (PCDATA)>
<!ELEMENT anyLlançament (PCDATA)>
<!ELEMENT personatges (personatge+)>
<!ELEMENT personatge (nom, rol)>
<!ELEMENT nom (PCDATA)>
<!ELEMENT rol (PCDATA)>

=== miquelmarques/LMSGI_DTD/RA01-RA04 Activitat/Exercisi1.b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "Exercisi1.b.dtd">
<joc>
    <titol>Final Fantasy VII</titol>
    <companyia>Square Enix</companyia>
    <plataforma>PlayStation</plataforma>
    <anyLlançament>1997</anyLlançament>
    <personatges>
        <personatge>
            <nom>Cloud Strife</nom>
            <rol>Protagonista</rol>
        </personatge>
        <personatge>
            <nom>Tifa Lockhart</nom>
            <rol>Suport</rol>
        </personatge>
        <personatge>
            <nom>Sephiroth</nom>
            <rol>Antagonista</rol>
        </personatge>
    </personatges>
</joc>
