=== miquelmarques/LMSGI_DTD/Exercisi1.c.dtd
<!ELEMENT joc (titol, companyia, plataforma+, anyLlançament, personatges, nivells)>
<!ELEMENT titol (PCDATA)>
<!ELEMENT companyia (PCDATA)>
<!ELEMENT plataforma (PCDATA)>
<!ELEMENT anyLlançament (PCDATA)>
<!ELEMENT personatges (personatge+ )>
<!ELEMENT personatge (nom, rol)>
<!ELEMENT rol (PCDATA)>
<!ELEMENT nivells (nivell+)>
<!ELEMENT nivell (nom)>
<!ELEMENT nom (PCDATA)>
<!ATTLIST personatge tipus CDATA #REQUIRED>
<!ATTLIST nivell dificultat (baixa|mitjana|alta) #REQUIRED>

=== miquelmarques/LMSGI_DTD/RA01-RA04 Activitat/Exercisi1.c.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE joc SYSTEM "Exercisi1.c.dtd">
<joc>
    <titol>Jak and Daxter: The Precursor Legacy</titol>
    <companyia>Naughty Dog</companyia>
    <plataforma>PlayStation 2</plataforma>
    <anyLlançament>2001</anyLlançament>
    <personatges>
        <personatge tipus="heroi">
            <nom>Jak</nom>
        </personatge>
        <personatge tipus="company">
            <nom>Daxter</nom>
        </personatge>
        <personatge tipus="mentora">
            <nom>Samos</nom>
        </personatge>
    </personatges>
    <nivells>
        <nivell dificultat="baixa">
            <nom>Geyser Rock</nom>
        </nivell>
        <nivell dificultat="mitjana">
            <nom>Sandover Village</nom>
        </nivell>
        <nivell dificultat="alta">
            <nom>Gol and Maia's Citadel</nom>
        </nivell>
    </nivells>
</joc>
